# Generated by Django 3.1.2 on 2020-12-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='place',
            name='open_time',
        ),
    ]
